# Accounts up-to-date as of February 17, 2014

cwpod = [ 'AFD', 'AIRFRANCE', 'ALCATELLUCENT', 'ARVALSL', 'ATOSATF', 'AUDATEX', 'AXAIM', 
'BASFSIRIUS', 'BASF', 'STYROLUTION', 'BASLER', 'BERTRANDT', 'BOEGOLD', 'BKW', 'SINGAPUR', 
'BOSCHPORTAL', 'BOSCH', 'BOSCHSI', 'BNK', 'BUSCH', 'CLAE', 'CANTONDEVAUD', 'CCIP', 'CHOREGIE', 
'CONSEILEUROPE', 'CRYSTAL', 'DANONEFRANSA', 'DCCSMAGNA', 'DEBEKA', 'DEGUSSA', 'DEKRA', 'DBINTRANET', 
'HRSD', 'DPEXTRANET', 'DIAKONIE', '3BEG', 'EADSCASS', 'EDFENERGY', 'EQUANTMSS', 'ERGOINS', 
'ESCPEXTRANET', 'ESPRIT', 'ETATDUVALAIS', 'FACHHOCHSCHULE', 'FERIBM', 'FEPEM', 'FEPEMWEB', 
'FONGECIF', 'WDR', 'GERRYWEBERIT', 'GFIMSA', 'GFITPG', 'HARMONIEMUTU', 'HUMANISINEAT', 
'GFZINTPORT', 'HZD', 'ICDCINTRANET', 'HANSEMERKUR', 'HAUFE', 'HAYSAG', 'IDEX', 'INFOGREFFE', 
'ISCECO', 'ISCECOAGATE', 'ISSA', 'ISTA', 'ITERGO', 'KLRUPPERT', 'KELAG', 'KLESIAINTER', 
'LISADRAXGMBH', 'AGEFOS', 'MCE', 'MERCKDEADELEOUS', 'MCC', 'MODFRANCE', 'MAEINTRANET', 
'MONEXT', 'ORANGEECE', 'ORANGECCSOL', 'PAGESJAUNESSA', 'PTCONSULTING', 'PREGO', 'P7S1P', 
'ROLEX', 'SAFEINTRANET', 'STGOBAIN', 'STGOBAINPLACO', 'SCHOTTINTRA', 'SCHUFA', 'SCHLLERMBELW', 
'SCHNEIDERSPICE', 'SGFGAS', 'MOBILIAR', 'SIEMENSAG', 'SOCIETEGEN', 'SOCIETE', 'SOGIPHARESER', 
'SOKA', 'SOPRAGROUPDII', 'SOPRAGROUPFOR', 'SNLT', 'STRAUMANNAG', 'STUTTGARTER', 'STYRIA', 
'SWISSLIFE', 'TSYSTEMSEHP', 'THALES', 'CHORUS', 'UNIVLAUSANNE', 'UKAINTRANET', 'UKRLP', 
'UNIGENEVA', 'VDMA', 'VEOLIA', 'VILLEDENIORT', 'VILOGIA', 'VAG', 'WWK' ];

sepod = [ 'ALBAHA', 'ALELM', 'ALELMEJAR', 'ALELMNAFETHA', 'ALNA', 'ATOSCZ', 'MEDIOLANUM', 
'BPMILANO', 'BIK', 'BREBANK', 'CAREL', 'COMARCHEHI', 'COMARCHJETBLUE', 'COOPITALIA', 'COSMOTE', 
'CSIPIEMONTE', 'DANONE', 'EMTAS', 'ESTONIANENERGY', 'ESTONIAN5G', 'EVERLIGHT', 'ECHA', 'EXPRIVIA', 
'FSECURE', 'FUJITSUFI', 'FUNDAMENTA', 'GOPLC', 'GOSI', 'HELLENIC', 'ITEAMOPAP', 'INFOCAMERE', 
'INFORMAZIONI', 'INNOVAPUGLIA', 'INTESASANPAOLO', 'INTRALOT', 'IMT', 'CSOB', 'KYIVSTAR', 
'LIETUVOSSD', 'LONDONSTOCK', 'MANDATUMLIFE', 'MAVIR', 'MAVIRINTRANET', 'METU', 'MEF', 
'MINISTINTERNO', 'MSCI', 'NBK', 'NOKIA', 'NOOVLE', 'OMANAIR', 'ONEWORLD', 'OPSERVICES', 
'PZUPORTAL', 'RAIFFEISENHR', 'RAIFFEISENHU', 'SANOMAVAUS', 'SINGULAR', 'SISALMATCHP', 
'SISALSLOT', 'SISAL', 'SMARTWAYTABUK', 'SOGEISPA', 'STCMYLINK', 'SOK', 'TALLINK', 'TELEFONICA', 
'ELEFONICAAM', 'UEF', 'CESKAREPUBLIKA', 'UNIVNAPOLI', 'VERNETOIMITUS', 'VIPNET', 'VIVACOM', 
'VODAFONEZRT', 'WFP' ];

npod = [ 'ACCENTURECLOUD', 'ARVALUK', 'ATOSUKSCC', 'BANQUELBLUX', 'BRITISHAIR', 'BUGABOO', 
'CGISWEDEN', 'CLOSEPREMIUM', 'CREDOCINTRA', 'CYCLEON', 'DELTALOYD', 'DEVON', 'ELLERINES', 
'TELENORCONN', 'ESSENTITBV', 'ETEX', 'EUROPEANCOMM', 'EMSA', 'ESA', 'EUROPOL', 'GENWORTHEU', 
'GRACO', 'BELGACOMVOO', 'HPBEETHOVEN', 'IMI', 'INTERNETSOL', 'INMARSAT', 'JOHNSONPORTAL', 
'JDWILLIAMS', 'KLM', 'LCHCLEARNET', 'LCHCLEARINTER', 'LRKBC', 'LONDONBOROUGH', 'MACH', 
'DICTUMINEZ', 'VGR', 'NTNU', 'DUNEA', 'NWO', 'ONS', 'OUN', 'OUNCWS', 'PVVIVIUM', 'PARKPHOENIX', 
'PBG', 'PARTENAMUT', 'PFIKSLGA', 'PROVANT', 'RADBOUD', 'RADISSON', 'REEDGLOBAL', 'RSPCA', 
'SBP', 'SPFFB', 'STICHTINGAPS', 'STICHHEEREN', 'THALESUK', 'TSB', 'TELENORNO', 'REVENUE', 
'UBMINFO', 'UNINETTAGORA', 'UNISYSUKLIM', 'UEA', 'UPPSALAUNI', 'UDSHBO', 'UZBRUSSEL', 'VTV', 
'VOCALINK', 'WKNLKOMES', 'WKNLTROIKA', 'WKOLSAT', 'WOODSAPIENT', 'WOODMACKENZIE' ];

print npod.length;


#### Archive ####

january = [ 'EDFENERGY', 'VILLEDENIORT', 'HELLENIC', 'PARKPHOENIX', 'PARKPHOENIX', 'PARKPHOENIX', 'PARKPHOENIX', 'AFD', 'PARKPHOENIX', 'PARKPHOENIX', 'PARKPHOENIX', 'PARKPHOENIX', 'PARKPHOENIX', 'VTV', 'PVVIVIUM', 'FERIBM', 'GOPLC', 'GOPLC', 'SBP', 'CONSEILEUROPE', 'DICTUMINEZ', 'BOEGOLD', 'SNLT', 'ETEX', 'LCHCLEARINTER', 'HAYSAG', 'SCHOTTINTRA', 'SISALMATCHP', 'BOEGOLD', 'BOEGOLD', 'STICHHEEREN', 'IMT', 'IMT', 'PTCONSULTING', 'LCHCLEARINTER', 'EUROPOL', 'PVVIVIUM', 'BOEGOLD', 'HAYSAG', 'EADSCASS', 'EADSCASS', 'EADSCASS', 'ATOSCZ', 'ATOSCZ', 'TALLINK', 'ISSA', 'STGOBAIN', 'ALELMEJAR', 'MEDIOLANUM', 'UEA', 'OUN', 'AFD', 'ONEWORLD', 'BOEGOLD', 'BOEGOLD', 'OUN', 'EDFENERGY', 'EDFENERGY', 'HAYSAG', 'PARKPHOENIX', 'PARKPHOENIX', 'PARKPHOENIX', 'STGOBAIN', 'MSCI', 'INTRALOT', 'EADSCASS', 'CSOB', 'MERCKDEADELEOUS', 'EUROPEANCOMM', 'CSOB', 'CSOB', 'INFOCAMERE', 'CSOB', 'SOK', 'CONSEILEUROPE', 'DELTALOYD', 'DELTALOYD', 'RAIFFEISENHR', 'SOCIETEGEN', 'RADBOUD', 'RADBOUD', 'ISCECO', 'TELENORNO', 'BOSCH', 'LCHCLEARINTER', 'LCHCLEARNET', 'LCHCLEARNET', 'DEKRA', 'DEKRA', 'VOCALINK', 'VOCALINK', 'HAUFE', 'MERCKDEADELEOUS', 'UNIVLAUSANNE', 'UNIVLAUSANNE', 'NTNU', 'ONEWORLD', 'SNLT', 'BOSCH', 'NBK', 'STGOBAIN', 'UNIVNAPOLI', 'UNIVNAPOLI', 'BOSCH', 'CSOB', 'EQUANTMSS', 'LONDONSTOCK', 'ETEX', 'ALCATELLUCENT', 'ISSA', 'LCHCLEARINTER', 'VAG', 'BOSCH', 'BOSCH', 'BOSCH', 'PARKPHOENIX', 'PARKPHOENIX', 'PARKPHOENIX', 'PARKPHOENIX', 'PARKPHOENIX', 'THALES', 'NTNU', 'SCHOTTINTRA', 'FERIBM', 'UEA', 'VAG', 'SCHNEIDERSPICE', 'SNLT', 'SNLT', 'EXPRIVIA', 'EXPRIVIA', 'EXPRIVIA', 'EXPRIVIA', 'PVVIVIUM', 'HELLENIC', 'ALCATELLUCENT', 'RADBOUD', 'RADBOUD', 'LCHCLEARINTER', 'INFOGREFFE', 'DANONEFRANSA', 'OPSERVICES', 'STICHHEEREN', 'AFD', 'FERIBM', 'OPSERVICES', 'SISALMATCHP', 'ATOSCZ', 'ATOSCZ', 'ALCATELLUCENT', 'CONSEILEUROPE', 'EADSCASS', 'HELLENIC', 'DANONEFRANSA', 'CSOB', 'DANONEFRANSA', 'EADSCASS', 'AFD', 'BOSCH', 'BOSCH', 'THALES', 'DEKRA', 'TELENORNO', 'VAG', 'BOEGOLD', 'EXPRIVIA', 'EXPRIVIA', 'HAYSAG', 'EXPRIVIA', 'EXPRIVIA', 'HAYSAG', 'FSECURE', 'UEA', 'SCHOTTINTRA', 'ESA', 'SCHOTTINTRA', 'SOGEISPA', 'UKAINTRANET', 'MONEXT', 'TELENORNO', 'STGOBAIN', 'DEKRA', 'DEKRA', 'IMT', 'IMT', 'IMT', 'STGOBAIN', 'UKAINTRANET', 'DELTALOYD', 'MCE', 'MCE', 'UZBRUSSEL', 'VAG', 'HAYSAG', 'HELLENIC', 'UNIVNAPOLI', 'UNIVNAPOLI', 'EADSCASS', 'EADSCASS', 'LCHCLEARINTER', 'MAEINTRANET', 'TSB', 'TSB', 'STGOBAIN', 'STICHHEEREN', 'ATOSUKSCC', 'AGEFOS', 'SCHOTTINTRA', 'SCHOTTINTRA', 'SNLT', 'TSB', 'ISCECO', 'LONDONBOROUGH', 'HAYSAG', 'NOOVLE', 'NOOVLE', 'DICTUMINEZ', 'DICTUMINEZ', 'CSOB', 'EDFENERGY', 'STICHHEEREN', 'ONEWORLD', 'LCHCLEARINTER', 'LCHCLEARINTER', 'ISCECOAGATE', 'HAYSAG', 'OPSERVICES', 'FEPEMWEB', 'FEPEMWEB', 'PTCONSULTING', 'SNLT', 'BOSCH', 'DEKRA', 'EDFENERGY', 'ONEWORLD', 'VAG', 'VOCALINK', 'HELLENIC', 'NWO', 'DEBEKA', 'BREBANK', 'LCHCLEARINTER', 'ONEWORLD', 'HUMANISINEAT', 'PTCONSULTING', 'CONSEILEUROPE', 'LCHCLEARNET', 'TSB', 'TSB', 'GOPLC', 'PVVIVIUM', 'FSECURE', 'SNLT', 'MANDATUMLIFE', 'STICHHEEREN', 'MEDIOLANUM', 'MAEINTRANET', 'FSECURE', 'FSECURE' ];

########

month = [ "EDFENERGY", "VILLEDENIORT", "HELLENIC", "PARKPHOENIX", "AFD", "PARKPHOENIX", "VTV", "PVVIVIUM", "FERIBM", "GOPLC", "SBP", "CONSEILEUROPE", "DICTUMINEZ", "BOEGOLD", "SNLT", "ETEX", "LCHCLEARINTER", "HAYSAG", "SCHOTTINTRA", "SISALMATCHP", "BOEGOLD", "BOEGOLD", "STICHHEEREN", "IMT", "PTCONSULTING", "LCHCLEARINTER", "EUROPOL", "PVVIVIUM", "BOEGOLD", "HAYSAG", "EADSCASS", "EADSCASS", "EADSCASS", "ATOSCZ", "TALLINK", "ISSA", "STGOBAIN", "ALELMEJAR", "MEDIOLANUM", "UEA", "OUN", "AFD", "ONEWORLD", "BOEGOLD", "OUN", "EDFENERGY", "HAYSAG", "PARKPHOENIX", "STGOBAIN", "MSCI", "INTRALOT", "EADSCASS", "CSOB", "MERCKDEADELEOUS", "EUROPEANCOMM", "CSOB", "INFOCAMERE", "CSOB", "SOK", "CONSEILEUROPE", "DELTALOYD", "RAIFFEISENHR", "SOCIETEGEN", "RADBOUD", "ISCECO", "TELENORNO", "BOSCH", "LCHCLEARINTER", "LCHCLEARNET", "DEKRA", "VOCALINK", "HAUFE", "MERCKDEADELEOUS", "UNIVLAUSANNE", "NTNU", "ONEWORLD", "SNLT", "BOSCH", "NBK", "STGOBAIN", "UNIVNAPOLI", "BOSCH", "CSOB", "EQUANTMSS", "LONDONSTOCK", "ETEX", "ALCATELLUCENT", "ISSA", "LCHCLEARINTER", "VAG", "BOSCH", "PARKPHOENIX", "THALES", "NTNU", "SCHOTTINTRA", "FERIBM", "UEA", "VAG", "SCHNEIDERSPICE", "SNLT", "EXPRIVIA", "PVVIVIUM", "HELLENIC", "ALCATELLUCENT", "RADBOUD", "LCHCLEARINTER", "INFOGREFFE", "DANONEFRANSA", "OPSERVICES", "STICHHEEREN", "AFD", "FERIBM", "OPSERVICES", "SISALMATCHP", "ATOSCZ", "ATOSCZ", "ALCATELLUCENT", "CONSEILEUROPE", "EADSCASS", "HELLENIC", "DANONEFRANSA", "CSOB", "DANONEFRANSA", "EADSCASS", "AFD", "BOSCH", "BOSCH", "THALES", "DEKRA", "TELENORNO", "VAG", "BOEGOLD", "EXPRIVIA", "HAYSAG", "EXPRIVIA", "HAYSAG", "FSECURE", "UEA", "SCHOTTINTRA", "ESA", "SCHOTTINTRA", "SOGEISPA", "UKAINTRANET", "MONEXT", "TELENORNO", "STGOBAIN", "DEKRA", "IMT", "STGOBAIN", "UKAINTRANET", "DELTALOYD", "MCE", "UZBRUSSEL", "VAG", "HAYSAG", "HELLENIC", "UNIVNAPOLI", "EADSCASS", "LCHCLEARINTER", "MAEINTRANET", "TSB", "STGOBAIN", "STICHHEEREN", "ATOSUKSCC", "AGEFOS", "SCHOTTINTRA", "SNLT", "TSB", "ISCECO", "LONDONBOROUGH", "HAYSAG", "NOOVLE", "DICTUMINEZ", "CSOB", "EDFENERGY", "STICHHEEREN", "ONEWORLD", "LCHCLEARINTER", "ISCECOAGATE", "HAYSAG", "OPSERVICES", "FEPEMWEB", "PTCONSULTING", "SNLT", "BOSCH", "DEKRA", "EDFENERGY", "ONEWORLD", "VAG", "VOCALINK", "HELLENIC", "NWO", "DEBEKA", "BREBANK", "LCHCLEARINTER", "ONEWORLD", "HUMANISINEAT", "PTCONSULTING", "CONSEILEUROPE", "LCHCLEARNET", "TSB", "GOPLC", "PVVIVIUM", "FSECURE", "SNLT", "MANDATUMLIFE", "STICHHEEREN", "MEDIOLANUM", "MAEINTRANET", "FSECURE" ];

cwcount = 0;
secount = 0;
ncount = 0;
notcount = 0;
allcount = 0;

shouldPrint = False;


for s in month:
	if s in cwpod:
		cwcount += 1;
		if shouldPrint:
			print 'CW-POD'
	elif s in sepod:
		secount += 1;
		if shouldPrint:
			print 'SE-POD'
	elif s in npod:
		ncount += 1;
		if shouldPrint:
			print 'N-POD'
	else:
		notcount += 1;
		if shouldPrint:
			print 'NOT-FOUND: %s' % s

if shouldPrint == False:
	allcount = cwcount + secount + ncount + notcount;
	print "Number of CW tickets opened: %s" % cwcount;
	print "Number of N  tickets opened: %s" % ncount;
	print "Number of SE tickets opened: %s" % secount;
	print "Number of not found tickets: %s" % notcount;
	print "Number of all opened tickets: %s" % allcount;
