#!/bin/bash

case $1 in
'c')
	mysql -u root -proot -e "create database $2 charset utf8;"
	;;
'd')
	mysql -u root -proot -e "drop database $2;"
	;;
'rc')
	mysql -u root -proot -e "drop database $2;create database $2 charset utf8;"
	;;
*)
	mysql -u root -proot
	;;
esac

