#!/bin/bash

if [[ $# -ne 1 ]]; then
	echo "Need the PID of the running process to dump the heap.";
	exit
fi

if [[ $1 == "help" ]]; then
	echo "Dumps the heapdump to the current directory. Only needs the <pid> of the running portal."
	exit
fi

date=$(date +"%Y%m%d_%H%M")

jmap -dump:format=b,file=heapdump_$date.hprof $1
