#!/bin/bash

case $1 in
'i')
	./patching-tool/patching-tool.sh $2 install
	;;
'a')
	./patching-tool/patching-tool.sh auto-discovery
	;;
'r')
	./patching-tool/patching-tool.sh $2 revert
	;;
*)
	./patching-tool/patching-tool.sh $2 info
	;;
esac

